steps:
  # Step 1: Build the function
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "bash"
    args: ["-c", "npm install"]

  # Step 2: Deploy the function
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "function-3"
      - "--entry-point"
      - "beforeCreate"
      - "--runtime"
      - "nodejs18"
      - "--trigger-http"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY
