steps:
  # Step 1: Build the function
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "bash"
    args: ["-c", "npm install"]

  # Step 2: Deploy the function
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "helloWorld"
      - "--entry-point"
      - "helloWorld"
      - "--runtime"
      - "nodejs16" # or the appropriate runtime version
      - "--trigger-http"
      - "--allow-unauthenticated" # Optional, allows unauthenticated access
